# Generated by Django 3.2 on 2021-04-20 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=80000)),
                ('recording', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
