# Generated by Django 3.1.7 on 2021-03-21 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recordings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, max_length=80000, null=True)),
                ('recording', models.FileField(upload_to=recordings.models.Recording.upload_path)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
